blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('', views.archive_blog, name="archive_blog"),
    path('category/<tag>', views.blog_by_tag, name="blog_by_tag"),
    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name="post_detail"),
    path('search/', views.search, name="search"),
    path('comment/', views.leave_comment, name="comment")

]

modern/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {'posts': PostSitemap}

urlpatterns = [
    path('', include('pages.urls', namespace='')),
    path('blog/', include('blog.urls', namespace='')),
    path('admin/', admin.site.urls),
    path('summernote', include('django_summernote.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse
from django.core.validators import FileExtensionValidator


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Tag(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    thumbnail = models.FileField(upload_to='images/%Y/%m/%d',
                                 validators=[FileExtensionValidator(['png', 'jpg', 'svg'])],
                                 verbose_name='Изображение',
                                 help_text='Поддерживаются форматы: .png, .jpg, .svg',
                                 blank=True,
                                 null=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog_by_tag', args=[self.slug])


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Черновик'),
        ('published', 'Опубликовано'),
    )
    title = models.CharField(verbose_name='Заголовок', max_length=250)
    slug = models.SlugField(verbose_name='Слаг', max_length=250, unique_for_date='publish')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='blog_posts',
                               editable=False, blank=True, null=True, verbose_name='Автор')
    category = models.ForeignKey(Tag, verbose_name='Категория', on_delete=models.SET_NULL, null=True)
    thumbnail = models.ImageField(upload_to='images/%Y/%m/%d')
    content = models.TextField(verbose_name="Контент", blank=True)
    excerpt = models.TextField(verbose_name='Краткое описание', max_length=500)

    status = models.CharField(verbose_name="Статус", max_length=15, choices=STATUS_CHOICES, default='draft')
    publish = models.DateTimeField(verbose_name="Опубликовано", default=timezone.now)
    created = models.DateTimeField(verbose_name="Создано", auto_now_add=True)
    updated = models.DateTimeField(verbose_name="Оновлено", auto_now=True)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

comments/models.py
from django.db import models
from blog.models import Post


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Comment(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Ждет модерации'),
        ('published', 'Опубликовано'),
    )
    name = models.CharField(verbose_name='Имя', max_length=50)
    surname = models.CharField(verbose_name='Фамилия', max_length=50)
    comment = models.TextField(verbose_name='Комментарий')
    reply = models.ForeignKey('self', verbose_name='Ответ на комментарий', blank=True, on_delete=models.CASCADE,
                              related_name='replied_comments',
                              null=True)
    post = models.ForeignKey(Post, verbose_name='Запись с Блога', related_name='post_comments',
                             on_delete=models.CASCADE)
    publish = models.DateTimeField(auto_now_add=True)
    status = models.CharField(verbose_name='Статус', max_length=15, choices=STATUS_CHOICES, default='published')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.comment

    def full_name(self):
        return f'{self.name} {self.surname}'

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Tag
from comments.models import Comment
from . import utils
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from .common.decorators import ajax_required
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank


def archive_blog(request):
    tags = utils.get_tags()
    posts_list = Post.published.all()
    paginator = Paginator(posts_list, 16)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    latest_posts = utils.get_latest_posts()
    context = {
        'page': page,
        'posts': posts,
        'page_name': 'Статьи',
        'post_type': 'archive',
        'tags': tags,
        'current_tag': None,
        'latest_posts': latest_posts
    }
    return render(request, 'blog/archive.html', context)


def blog_by_tag(request, tag):
    current_tag = Tag.objects.get(slug=tag)
    tags = utils.get_tags()
    posts_list = Post.published.filter(category__slug=tag)
    paginator = Paginator(posts_list, 16)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    latest_posts = utils.get_latest_posts()
    context = {
        'page': page,
        'posts': posts,
        'page_name': current_tag.title,
        'post_type': 'archive',
        'tags': tags,
        'current_tag': tag,
        'latest_posts': latest_posts
    }
    return render(request, 'blog/archive.html', context)


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month,
                             publish__day=day)
    comments = Comment.published.filter(post__pk=post.pk).order_by('publish')
    related_posts = False
    try:
        related_posts = Post.published.filter(category=post.category).exclude(pk=post.pk).order_by('-publish')[:10]
    except:
        pass

    context = {
        'post': post,
        'page_name': post.title,
        'post_type': 'single',
        'comments': comments,
        'related_posts': related_posts
    }
    return render(request, 'blog/single.html', context)


@ajax_required
@require_POST
def leave_comment(request):
    name = request.POST.get('name')
    surname = request.POST.get('surname')
    msg = request.POST.get('msg')
    reply = request.POST.get('reply')
    post = Post.objects.get(pk=int(request.POST.get('post')))
    if not name or not surname or not msg or not post:
        return JsonResponse({'status': 'error'})

    comment = Comment()
    comment.name = name
    comment.surname = surname
    comment.comment = msg
    comment.post = post

    replied_comment = False

    try:
        replied_comment = Comment.objects.get(pk=int(reply))
    except:
        pass

    if replied_comment:
        comment.reply = replied_comment

    comment.save()

    if comment.pk:
        response = {
            'status': 'ok',
            'data': {
                'id': comment.pk,
                'msg': comment.comment,
                'full_name': comment.full_name(),
                'time': comment.publish,
            }
        }
        if replied_comment:
            response['data']['replied_comment'] = {
                'id': replied_comment.pk,
                'msg': replied_comment.comment,
                'time': replied_comment.publish,
                'full_name': replied_comment.full_name()
            }
        return JsonResponse(response)
    else:
        return JsonResponse({'status': 'error'})


def search(request):

    search_header = None
    if 'query' in request.GET:
        query = request.GET['query']
        search_header = f'Результаты поиска: <em>"{query}"</em>'
        search_vector = SearchVector('title', weight='A') + SearchVector('content', weight='B')
        search_query = SearchQuery(query)
        latest_posts = Post.published.annotate(
            search=search_vector,
            rank=SearchRank(search_vector, search_query)
        ).filter(rank__gte=0.3).order_by('-rank')
    else:
        latest_posts = Post.published.all()[:4]

    context = {
        'page_name': 'Поиск',
        'post_type': 'archive',
        'current_tag': None,
        'latest_posts': latest_posts,
        'search_header': search_header,
    }
    return render(request, 'blog/search.html', context)

comments/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/archive.html
{% extends 'layout/base.html' %}

{% block title %}{{page_name}}{% endblock %}

{% block breadcrumbs %}
    {% include 'breadcrumbs.html' %}
{% endblock %}

{% block content %}
<main class="cats-main">
    <div class="container">
        <div class="section-header">
            <h1 class="section-header__title">
                {{ page_name }}
            </h1>
        </div>
        <div class="cats-main-wrapper">
            {% include 'blog/cats-aside.html' %}

            <div class="related-posts-wrapper">
                <ul class="related-posts">
                    {% for post in posts %}
                        <li class="related-posts__item related-post">
                            <div class="related-post__img">
                                <img src="{{ post.thumbnail.url }}" alt="пост">
                            </div>
                            <div class="related-post__info">
                                <h2 class="related-post__title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                                <time class="related-post__date">{{ post.publish | date:'d.m.Y' }}</time>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                {% if posts.paginator.num_pages > 1 %}
                    {% include 'blog/pagination.html' with page=posts %}
                {% endif %}
            </div>

        </div>
        </div>
    </div>
</main>

{% include 'blog/latest.html' %}

{% endblock %}

blog/templates/blog/cats-aside.html
<aside class="cats-aside">
    <ul class="cats-aside-group">
        {% for tag in tags %}
            <li class="cats-aside-group__item{% if tag.slug == current_tag %} active{% endif %}">
                <a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a>
            </li>
        {% endfor %}
    </ul>
</aside>

blog/templates/blog/comments.html
{% load static %}
<section class="single-post__comments">
    <div class="container">
        <div class="section-header">
            <h2 class="section-header__title">Комментарии (<span class="comments__cnt">{{ comments.count }}</span>)</h2>
        </div>
        <ul class="comments-group">
            {% for comment in comments %}
            <li id="comment-{{ comment.pk }}" class="comment-group__item comment">
                <div class="comment-wrapper">
                    <p class="comment__author">
                        <span>Автор: {{ comment.full_name }}</span>
                    </p>
                    <div class="comment__date">
                        <span>Дата: </span>
                        <time>{{ comment.publish | date:'d.m.Y' }}</time>
                    </div>
                    {% if comment.reply %}
                        <a href="#comment-{{ comment.reply.pk }}" class="comment__cite">
                            <p class="comment__author">
                                <span>От пользователя: {{ comment.reply.full_name }}</span>
                            </p>
                            <div class="comment__date">
                                <span>Дата: </span>
                                <time>{{ comment.reply.publish | date:'d.m.Y' }}</time>
                                <p class="comment-content">
                                    {{ comment.reply.comment | truncatechars:200 }}
                                </p>
                            </div>
                        </a>
                    {% endif %}

                    <p class="comment-content comment-content_origin">
                        {{ comment.comment }}
                    </p>

                    <button class="comment-reply" type="button" data-id="{{ comment.pk }}">Ответить</button>
                </div>
            </li>
            {% endfor %}
        </ul>
        <form action="{% url 'blog:comment' %}" class="form-comment">
            <h3 class="form-comment__title">Оставить комментарий</h3>
            <div class="replied-message">
                <button type="button" class="delete-replied-comment" aria-label="Закрыть">
                    <span></span>
                </button>
                <p class="replied-message__text"></p>
            </div>
            <div class="form-comment__fields">
                {% csrf_token %}
                <input class= type="text" name="name" placeholder="Ваше имя">
                <input type="text" name="surname" placeholder="Ваша фамилия">
                <input type="hidden" name="reply" value="">
                <input type="hidden" name="post" value="{{ post.pk }}">
                <textarea name="msg" cols="30" rows="10" placeholder="Коментарий" required value="test"></textarea>
                <button type="submit">
                    <span>Опубликовать</span>
                    <img src="{% static 'img/arrow-right-dark.svg' %}" alt="стрелка">
                </button>
            </div>
        </form>
    </div>
</section>

blog/templates/blog/latest.html
{% if latest_posts or page_name == "Поиск" %}
<section class="latest latest_secondary">
    <div class="container">
        <div class="section-header">
            <h2 class="section-header__title">
                {% if search_header %}
                    {{ search_header | safe }}
                {% else %}
                    Новое на форуме
                {% endif %}
            </h2>
        </div>
        {% if latest_posts %}
        <ul class="latest-group">
            {% for post in latest_posts %}
            <li class="latest-group__item latest-item">
                <div class="latest-item__thumb">
                    <img src="{{ post.thumbnail.url }}" alt="{{ post.title }}">
                </div>
                <div class="latest-item__info">
                    <h3 class="latest-item__title">
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </h3>
                    <p class="latest-item__excerpt">
                        {{ post.excerpt|truncatechars:165 }}
                    </p>
                    <div class="latest-item__controls">
                        {% if post.category %}
                        <a href="{{ post.category.get_absolute_url }}" class="latest-item__term">
                            {{ post.category.title }}
                        </a>
                        {% endif %}
                        <time class="latest-item__date">{{ post.publish | date:'d.m.Y' }}</time>
                    </div>
                </div>
                <p class="latest-item__excerpt__mobile">
                    {{ post.excerpt|truncatechars:165 }}
                </p>
            </li>
            {% endfor %}
        </ul>
        {% else %}
            <p>По вашему запросу статтей не найдено...</p>
        {% endif %}
    </div>
</section>
{% endif %}

blog/templates/blog/pagination.html
{% load static %}
<div class="related-posts__pagination">
    <nav class="pagination">
        {% if page.has_previous %}
            <a class="pagi-prev" href="?page={{ page.previous_page_number }}" aria-label="Предыдущая страница">
                <img src="{% static 'img/arrow-right.svg' %}" alt="стрелка">
            </a>
        {% endif %}
        <span>{{ page.number }}</span>
        {% if page.has_next %}
            <a class="pagi-next" href="?page={{ page.next_page_number }}" aria-label="Следующая страница">
                <img src="{% static 'img/arrow-right.svg' %}" alt="стрелка">
            </a>
        {% endif %}
    </nav>
</div>

blog/templates/blog/related-posts.html
{% if related_posts %}
    <aside class="single-aside">
        <h2 class="single-aside__title">Статьи с категории</h2>
        <ul class="single-aside__group">
            {% for related_post in related_posts %}
                <li class="single-aside__article">
                    <a href="{{ related_post.get_absolute_url }}">{{ related_post.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </aside>
{% endif %}

blog/templates/blog/search.html
{% extends 'layout/base.html' %}

{% block title %}{{page_name}}{% endblock %}

{% block breadcrumbs %}
    {% include 'breadcrumbs.html' %}
{% endblock %}

{% block content %}


{% include 'blog/latest.html' %}

{% endblock %}

blog/templates/blog/single.html
{% extends 'layout/base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block breadcrumbs %}
    {% include 'breadcrumbs.html' %}
{% endblock %}

{% block content %}
<main class="single-main">
    <div class="container">
        <article class="single-article">
            <h1 class="single-article__title">{{ post.title }}</h1>
            <div class="single-article__content">
                {{ post.content | safe }}
            </div>
            <div class="single-article__details">
                {% if post.updated != post.created %}
                <p class="single-article__update">
                    Последнеее обновление: {{ post.updated }}
                </p>
                {% endif %}
                <p class="single-article__created">
                    Дата создания: <time>{{ post.created | date:'d.m.Y' }}</time>
                </p>
                <p>Автор: <span>{% firstof post.author.get_full_name post.author.username %}</span></p>
            </div>
        </article>
        {% include 'blog/related-posts.html' %}
    </div>
</main>

{% include 'blog/comments.html' %}

{% endblock %}