blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('', views.archive_blog, name="archive_blog"),
    path('category/<tag>', views.blog_by_tag, name="blog_by_tag"),
    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name="post_detail"),
    path('search/', views.search, name="search"),
    path('comment/', views.leave_comment, name="comment")

]

modern/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {'posts': PostSitemap}

urlpatterns = [
    path('', include('pages.urls', namespace='')),
    path('blog/', include('blog.urls', namespace='')),
    path('admin/', admin.site.urls),
    path('summernote', include('django_summernote.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
app_name = 'pages'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('feadback/', views.feadback, name='feadback'),
    path('send-message/', views.send_message, name='send_message')
]

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse
from django.core.validators import FileExtensionValidator


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Tag(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    thumbnail = models.FileField(upload_to='images/%Y/%m/%d',
                                 validators=[FileExtensionValidator(['png', 'jpg', 'svg'])],
                                 verbose_name='Изображение',
                                 help_text='Поддерживаются форматы: .png, .jpg, .svg',
                                 blank=True,
                                 null=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog_by_tag', args=[self.slug])


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Черновик'),
        ('published', 'Опубликовано'),
    )
    title = models.CharField(verbose_name='Заголовок', max_length=250)
    slug = models.SlugField(verbose_name='Слаг', max_length=250, unique_for_date='publish')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='blog_posts',
                               editable=False, blank=True, null=True, verbose_name='Автор')
    category = models.ForeignKey(Tag, verbose_name='Категория', on_delete=models.SET_NULL, null=True)
    thumbnail = models.ImageField(upload_to='images/%Y/%m/%d')
    content = models.TextField(verbose_name="Контент", blank=True)
    excerpt = models.TextField(verbose_name='Краткое описание', max_length=500)

    status = models.CharField(verbose_name="Статус", max_length=15, choices=STATUS_CHOICES, default='draft')
    publish = models.DateTimeField(verbose_name="Опубликовано", default=timezone.now)
    created = models.DateTimeField(verbose_name="Создано", auto_now_add=True)
    updated = models.DateTimeField(verbose_name="Оновлено", auto_now=True)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Tag
from comments.models import Comment
from . import utils
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from .common.decorators import ajax_required
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank


def archive_blog(request):
    tags = utils.get_tags()
    posts_list = Post.published.all()
    paginator = Paginator(posts_list, 16)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    latest_posts = utils.get_latest_posts()
    context = {
        'page': page,
        'posts': posts,
        'page_name': 'Статьи',
        'post_type': 'archive',
        'tags': tags,
        'current_tag': None,
        'latest_posts': latest_posts
    }
    return render(request, 'blog/archive.html', context)


def blog_by_tag(request, tag):
    current_tag = Tag.objects.get(slug=tag)
    tags = utils.get_tags()
    posts_list = Post.published.filter(category__slug=tag)
    paginator = Paginator(posts_list, 16)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    latest_posts = utils.get_latest_posts()
    context = {
        'page': page,
        'posts': posts,
        'page_name': current_tag.title,
        'post_type': 'archive',
        'tags': tags,
        'current_tag': tag,
        'latest_posts': latest_posts
    }
    return render(request, 'blog/archive.html', context)


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month,
                             publish__day=day)
    comments = Comment.published.filter(post__pk=post.pk).order_by('publish')
    related_posts = False
    try:
        related_posts = Post.published.filter(category=post.category).exclude(pk=post.pk).order_by('-publish')[:10]
    except:
        pass

    context = {
        'post': post,
        'page_name': post.title,
        'post_type': 'single',
        'comments': comments,
        'related_posts': related_posts
    }
    return render(request, 'blog/single.html', context)


@ajax_required
@require_POST
def leave_comment(request):
    name = request.POST.get('name')
    surname = request.POST.get('surname')
    msg = request.POST.get('msg')
    reply = request.POST.get('reply')
    post = Post.objects.get(pk=int(request.POST.get('post')))
    if not name or not surname or not msg or not post:
        return JsonResponse({'status': 'error'})

    comment = Comment()
    comment.name = name
    comment.surname = surname
    comment.comment = msg
    comment.post = post

    replied_comment = False

    try:
        replied_comment = Comment.objects.get(pk=int(reply))
    except:
        pass

    if replied_comment:
        comment.reply = replied_comment

    comment.save()

    if comment.pk:
        response = {
            'status': 'ok',
            'data': {
                'id': comment.pk,
                'msg': comment.comment,
                'full_name': comment.full_name(),
                'time': comment.publish,
            }
        }
        if replied_comment:
            response['data']['replied_comment'] = {
                'id': replied_comment.pk,
                'msg': replied_comment.comment,
                'time': replied_comment.publish,
                'full_name': replied_comment.full_name()
            }
        return JsonResponse(response)
    else:
        return JsonResponse({'status': 'error'})


def search(request):

    search_header = None
    if 'query' in request.GET:
        query = request.GET['query']
        search_header = f'Результаты поиска: <em>"{query}"</em>'
        search_vector = SearchVector('title', weight='A') + SearchVector('content', weight='B')
        search_query = SearchQuery(query)
        latest_posts = Post.published.annotate(
            search=search_vector,
            rank=SearchRank(search_vector, search_query)
        ).filter(rank__gte=0.3).order_by('-rank')
    else:
        latest_posts = Post.published.all()[:4]

    context = {
        'page_name': 'Поиск',
        'post_type': 'archive',
        'current_tag': None,
        'latest_posts': latest_posts,
        'search_header': search_header,
    }
    return render(request, 'blog/search.html', context)

blog/templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no">
    <title>{% block title %}Главная{% endblock %} - ModernGIS</title>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="wrapper">

        <div class="content">
            <header class="header">
                <div class="container">
                    <div class="header__row">
                        <div class="mobile-menu">
                            <button type="button" aria-label="Открыть мобильное меню">
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                            </button>
                            <ul class="header__menu_mobile">
                                <li{% if post_type == 'archive' %} class="active"{% endif %}><a href="{% url 'blog:archive_blog' %}">Статьи</a></li>
                                <li{% if post_type == 'about' %} class="active"{% endif %}><a href="{% url 'pages:about' %}">Об авторе</a></li>
                                <li{% if post_type == 'feadback' %} class="active"{% endif %}><a href="{% url 'pages:feadback' %}">Обратная связь</a></li>
                            </ul>
                        </div>

                        <a href="{% url 'pages:home' %}" class="header__logo">
                            <img src="{% static 'img/logo.svg' %}" alt="логотип">
                        </a>
                        <div class="header__menu-search">
                            <ul class="header__menu">
                                <li{% if post_type == 'archive' %} class="active"{% endif %}><a href="{% url 'blog:archive_blog' %}">Статьи</a></li>
                                <li{% if post_type == 'about' %} class="active"{% endif %}><a href="{% url 'pages:about' %}">Об авторе</a></li>
                                <li{% if post_type == 'feadback' %} class="active"{% endif %}><a href="{% url 'pages:feadback' %}">Обратная связь</a></li>
                            </ul>
                            <form class="header__form header-form" action="{% url 'blog:search' %}" method="GET">
                                <input type="text" class="header-form__input" name="query"{% if request.GET.query %} value="{{ request.GET.query }}"{% endif %}>
                                <button type="submit" aria-label="искать"><img src="{% static 'img/search.svg' %}" alt="поиск"></button>
                            </form>
                        </div>
                    </div>
                </div>
            </header>

            {% block breadcrumbs %} {% endblock %}

            {% block content %} {% endblock %}

        </div>
        <!-- /.content -->

        <footer class="footer">
            <div class="container">
                <p class="footer__copy">
                    <img src="{% static 'img/copy.svg' %}" alt="знак копирования">
                    <span>Все права защищены</span>
                </p>
            </div>
        </footer>
    </div>
    <!-- /.wrapper -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>