blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('', views.archive_blog, name="archive_blog"),
    path('category/<tag>', views.blog_by_tag, name="blog_by_tag"),
    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name="post_detail"),
    path('search/', views.search, name="search"),
    path('comment/', views.leave_comment, name="comment")

]

modern/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {'posts': PostSitemap}

urlpatterns = [
    path('', include('pages.urls', namespace='')),
    path('blog/', include('blog.urls', namespace='')),
    path('admin/', admin.site.urls),
    path('summernote', include('django_summernote.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
app_name = 'pages'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('feadback/', views.feadback, name='feadback'),
    path('send-message/', views.send_message, name='send_message')
]

pages/templates/pages/about.html
{% extends 'layout/base.html' %}
{% load static %}

{% block title %}{{page_name}}{% endblock %}

{% block breadcrumbs %}
    {% include 'breadcrumbs.html' %}
{% endblock %}


{% block content %}
<main class="about-main">
    <div class="container">
        <div class="section-header">
            <h1 class="section-header__title">
                {{ page_name }}
            </h1>
        </div>

        <div class="about-text">
            <p class="author-name">
                {{ page.name }}
            </p>
            <div class="about-img">
                <img src="{{ page.thumbnail.url }}" alt="{{ page.name }}">
            </div>

            <h2 class="author-subtitle">
                {{ page.excerpt }}
            </h2>

            <div class="about-content">
                {{ page.content | safe }}
            </div>


        </div>



    </div>
</main>
{% endblock %}

pages/templates/pages/feadback.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}{{page_name}}{% endblock %}

{% block breadcrumbs %}
    {% include 'breadcrumbs.html' %}
{% endblock %}

{% block content %}
    <main class="main-feadback">
        <div class="container">
            <div class="feadback__row">
                <div class="feadback__img">
                    <img src="{% static 'img/feadback.png' %}" alt="мозг">
                </div>
                <form action="{% url 'pages:send_message' %}" class="feadback-form">
                    <div class="section-header">
                        <h1 class="section-header__title">
                            Возникли вопросы или предложения?
                        </h1>
                    </div>
                    <div class="feadback-form__fields">
                        {% csrf_token %}
                        <input type="text" name="name" required placeholder="Ваше имя">
                        <input type="email" name="email" required placeholder="Ваш e-mail">
                        <textarea name="comment" cols="30" rows="10" placeholder="Ваш комментарий"></textarea>
                        <button type="submit">
                            <span>Отправить</span>
                            <img src="{% static 'img/arrow-right-dark.svg' %}" alt="стрелка">
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </main>
{% endblock %}

pages/templates/pages/index.html
{% extends 'layout/base.html' %}

{% load static %}

{% block content %}
<main class="banner">
    <div class="container">
        <div class="banner__row">
            <div class="stages">
                <div class="stages__item"></div>
                <div class="stages__item"></div>
                <div class="stages__item"></div>
                <div class="stages__item active"></div>
                <div class="stages__item"></div>
            </div>
            <div class="banner__video-box">
                <video class="banner__video" autoplay muted loop>
                    <source src="{% static 'video/Globe - 5925.mp4' %}" type="video/mp4">
                </video>
            </div>
            <div class="banner__header">
                <h1 class="banner__header_title">ArcGis Pro</h1>
                <a class="link link_border" href="{% url 'blog:archive_blog' %}">
                    <span>Смотреть все категории</span>
                    <img src="{% static 'img/arrow-right.svg' %}" alt="стрелка">
                </a>
            </div>
        </div>
    </div>
</main>

{% include 'blog/latest.html' %}

{% include 'pages/main-terms.html' %}

{% include 'pages/random-article.html' with posts=random_article %}

{% endblock %}

pages/templates/pages/main-terms.html
{% load static %}
{% if tags %}
    <section class="terms-section">
        <div class="container">
            <div class="section-header">
                <h2 class="section-header__title">Категории</h2>
                <div class="section-header__controls">
                    <button class="term-arrow prev" type="button" class="предыдущий слайд">
                        <img src="{% static 'img/arrow-right-big.svg' %}" alt="стрелка">
                    </button>
                    <button class="term-arrow next" type="button" class="следующий слайд">
                        <img src="{% static 'img/arrow-right-big.svg' %}" alt="стрелка">
                    </button>
                </div>
            </div>
            <ul class="terms-group" data-index="1">
                {% for tag in tags %}
                    <li class="terms-group__item term-item">
                        <a href="{{ tag.get_absolute_url }}">
                            <div class="term-item__thumb">
                                <img src="{{ tag.thumbnail.url }}" alt="{{ tag.title }}">
                            </div>
                            <h3 class="term-item__title">{{ tag.title }}</h3>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </section>
{% endif %}

pages/templates/pages/random-article.html
{% load static %}
{% if posts %}
    <section class="random-article">
        <div class="container">
            {% for post in posts %}
                <div class="random-article__info">
                    <h2 class="random-article__title">{{ post.title }}</h2>
                    <p class="random-article__desc">
                        {{ post.excerpt }}
                    </p>
                    <a class="link link_border" href="{{ post.get_absolute_url }}">
                        <span>Читать статью</span>
                        <img src="{% static 'img/arrow-right.svg' %}" alt="стрелка">
                    </a>
                </div>
                {% if post.thumbnail %}
                    <div class="random-article__thumb">
                        <img src="{{ post.thumbnail.url }}" alt="картинка">
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </section>
{% endif %}